name: MySQL Windows Test

on:
  workflow_dispatch:

jobs:
  mysql:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Initialize MySQL
        shell: powershell
        run: .\scripts\setup-mysql.ps1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run application
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 32768
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: my_db
        run: python main.py