name: WSL Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Install Ubuntu
      run: |
        wsl --install Ubuntu

    - name: Check distro
      run: |
        wsl -l -v